### ISSUE TITLE
Hello Console

### ISSUE THREAD

**Issue by TonyZOtto** [TonyZOtto/INDIface6#2]
In support of v6,89A:

- Setup repository directory structure 
  - [x] ./src
    - [x] ./libs
      - [x] ./eIRbase
      - [x] ./eIRcore
      - [x] ./eIRexe
    - [x] ./console
      - [x] ./If6Console
- [x] Create Console Application
- [x] Bring over `VersionInfo`
- [x] Bring over `version,.h`
- [x] Create `version.pri`
- [x] Setup `DESTDIR.pri` environment [#3]
- [x] Bring over logging [#4]
- [x] Bring over command line [#5]
- [x] Bring over application settings [#6]
- [x] Start application initialization [#7]
